#import "../fragments/UserPostInfo.gql"
#import "../fragments/PostComments.gql"

query allPosts {
  allPosts(orderBy: updatedAt_DESC) {
    id
    createdAt
    body
    ...UserPostInfo
    ...PostComments
  }
}