#import "../fragments/PostComments.gql"
#import "../fragments/UserProfile.gql"
#import "../fragments/UserPostInfo.gql"


query User($username: String!) {
  User(username: $username) {
    ...UserProfile
    posts(orderBy: createdAt_DESC) {
      id
      createdAt
      body
      ...UserPostInfo
      ...PostComments
    }
  }
}